### ISSUE TITLE
Multiple django 2.0 incompatibilities

### ISSUE THREAD

**Issue by SalahAdDin** [django-erp/django-erp#33]
Hello guys,

I have the next error trying to migrate in `django` 2.0: 
```bash
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/Works/recipes/erp/django-erp/djangoerp/pluggets/apps.py", line 23, in <module>
    from .loading import registry
  File "/home/salahaddin/Proyectos/Works/recipes/erp/django-erp/djangoerp/pluggets/loading.py", line 22, in <module>
    from djangoerp.core.cache import Singleton
  File "/home/salahaddin/Proyectos/Works/recipes/erp/django-erp/djangoerp/core/cache.py", line 21, in <module>
    from django.contrib.auth.models import AnonymousUser
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
When i remove all `django-erp` apps i get the next error:
```bash
/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/urls/conf.py", line 17, in include
    urlconf_module, app_name = arg
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/Works/recipes/erp/django-erp/djangoerp/urls.py", line 46, in <module>
    url(r'^admin/', include(admin.site.urls))
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/urls/conf.py", line 27, in include
    'provide the namespace argument to include() instead.' % len(arg)
django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.
```

**Comment by SalahAdDin** [comment]
I made the change to a `django` 1.8.19, and i get the next error:
```bash
./manage.py migrate                     1 ↵  2663  13:09:38 
/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/lib/python3.6/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/salahaddin/Proyectos/Works/recipes/erp/django-erp/djangoerp/core/utils/apps.py", line 47, in ready
    self.signals = __import__("%s.signals" % self.name, {}, {}, ["*"])
  File "/home/salahaddin/Proyectos/Works/recipes/erp/django-erp/djangoerp/menus/signals.py", line 70, in <module>
    manage_bookmarks(settings.AUTH_USER_MODEL)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/django-erp/djangoerp/menus/signals.py", line 51, in manage_bookmarks
    cls = get_model(cls)
  File "/home/salahaddin/Proyectos/Works/recipes/erp/django-erp/djangoerp/core/utils/models.py", line 54, in get_model
    elif isinstance(klass, basestring):
NameError: name 'basestring' is not defined
```
It is a problem with `python` 3.x, so, also this package it is not supported by `python` 3.x.

**Comment by zuck** [comment]
Should be fixed now
